model:
  target_model_path: Qwen/Qwen2.5-32B
  embedding_key: model.language_model.embed_tokens.weight
  lm_head_key: lm_head.weight
  norm_key: model.language_model.norm.weight
  trust_remote_code: true
  draft_model_config: "/home/jpollok/draft-model-for-LLMs/configs/draft_config.json"



dataset:
  train_data_path: "/home/jpollok/.cache/random_5k_samples_0.9m.jsonl"
  eval_data_path: "/home/jpollok/.cache/random_50_samples_0.5m.jsonl"
  eval_interval: 200
  chat_template: qwen
  prompt_key: messages
  defer_tokenization: false

logging:
  report_to: wandb
  use_wandb: true
  wandb_project: "27B-Training-3Tokens"
  wandb_mode: online

training:
  attention_backend: fa4
  micro_batch_size: 2
  draft_accumulation_steps: 1
  learning_rate: 3e-4
  num_train_steps: 10000
  max_concurrent_batches: 2
  max_grad_norm: 2.0
  max_seq_length: 32000
  num_epochs: 3
  seed: 42
  training_num_gpus_per_node: 8
  training_num_nodes: 1
  ttt_length: 3
  save_per_epoch: true
  warmup_ratio: 0.015
  save_interval: 1000
  fsdp_strategy: FULL_SHARD
  fsdp_reduce_dtype: bfloat16

inference:
  inference_engine_type: vllm
  inference_num_gpus: 8
  inference_num_gpus_per_engine: 8
  inference_num_gpus_per_node: 8
  max_sample_pool_size: 32
  inference_buffer_threshold: 32
  inference_batch_size: 2
  aux_hidden_states_layers: [3, 19, 35]
  vllm:
    tp_size: 8
    mem_fraction_static: 0.8
    extra_args:
      language_model_only: true
      max_num_batched_tokens: 512
      max_num_seqs: 2
      max_model_len: 18000
      enable_chunked_prefill: true
      enforce_eager: true
      cpu_offload_gb: 12

mooncake:
  enable: false
  protocol: tcp
  master_server_address: "134.2.17.206:51783"
  metadata_server: "http://134.2.17.206:8580"
  global_segment_size: 8GB
  local_buffer_size: 1GB


output_dir: /home/jpollok/.cache/outputs/qwen3_5-27b-single-node
cache_dir: /home/jpollok/.cache/qwen3_5-27b-single-node
model_download_dir: null

